"""
merge_zone_criteria.py
Reads the 3 zone criteria JSON files and generates:
  - 01b_ZoneData.js  (criteria data for GAS)
  - zone_metadata.txt (leader/supervisor/floor per zone, for updating 01_Config.js)
"""
import json, os, textwrap

MEMORY = r"C:\Users\Appex\.claude\projects\C--Users-Appex-My-Drive--packmasters-mumbai-gmail-com--PackMasters-5sSystem\memory"
OUT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # project root

FILES = [
    os.path.join(MEMORY, "zones-criteria.json"),
    os.path.join(MEMORY, "zones-criteria-1f-2f.json"),
    os.path.join(MEMORY, "zones-criteria-2f.json"),
]

AUDIT_DAYS = {
    "Z-01": ("Monday", 1),    "Z-02": ("Monday", 1),    "Z-03": ("Monday", 1),
    "Z-04": ("Tuesday", 2),   "Z-05": ("Tuesday", 2),   "Z-06": ("Tuesday", 2),
    "Z-07": ("Wednesday", 3), "Z-08": ("Wednesday", 3), "Z-09": ("Wednesday", 3),
    "Z-10": ("Thursday", 4),  "Z-11": ("Thursday", 4),  "Z-12": ("Thursday", 4),
    "Z-13": ("Friday", 5),    "Z-14": ("Friday", 5),    "Z-15": ("Friday", 5),
    "Z-16": ("Monday", 1),    "Z-17": ("Monday", 1),    "Z-18": ("Monday", 1),
    "Z-19": ("Tuesday", 2),   "Z-20": ("Tuesday", 2),   "Z-21": ("Tuesday", 2),
    "Z-22": ("Wednesday", 3), "Z-23": ("Wednesday", 3), "Z-24": ("Wednesday", 3),
    "Z-25": ("Thursday", 4),  "Z-26": ("Thursday", 4),  "Z-27": ("Thursday", 4),
    "Z-28": ("Friday", 5),
}

DEPARTMENTS = {
    "Z-01": "Security & Logistics",  "Z-02": "Security & Logistics",
    "Z-03": "Production & Ops",      "Z-04": "Production & Ops",
    "Z-05": "Production & Ops",      "Z-06": "Security & Logistics",
    "Z-07": "Facilities & Maintenance", "Z-08": "Production & Ops",
    "Z-09": "Facilities & Maintenance", "Z-10": "Administration",
    "Z-11": "Administration",        "Z-12": "Administration",
    "Z-13": "Administration",        "Z-14": "Quality & Compliance",
    "Z-15": "Production & Ops",      "Z-16": "Stores & Inventory",
    "Z-17": "Stores & Inventory",    "Z-18": "Stores & Inventory",
    "Z-19": "Stores & Inventory",    "Z-20": "Facilities & Maintenance",
    "Z-21": "Facilities & Maintenance", "Z-22": "Production & Ops",
    "Z-23": "Facilities & Maintenance", "Z-24": "Production & Ops",
    "Z-25": "Production & Ops",      "Z-26": "Production & Ops",
    "Z-27": "Stores & Inventory",    "Z-28": "Stores & Inventory",
}

EMAILS = {
    "Mr. Tarun":          "tarun@packmasters.in",
    "Mr. Anuj Pathak":    "anuj.pathak@packmasters.in",
    "Mrs. Shikha":        "shikha@packmasters.in",
    "Mr. Balkrishna":     "balkrishna@packmasters.in",
    "Mrs. Khushi Paswan": "khushi.paswan@packmasters.in",
    "Mr. Santosh Maurya": "santosh.maurya@packmasters.in",
}

def js_str(s):
    return json.dumps(str(s), ensure_ascii=False)

def main():
    # 1. Merge all 3 JSON files
    merged = {}
    for f in FILES:
        with open(f, encoding="utf-8") as fh:
            merged.update(json.load(fh))

    zone_ids = sorted(merged.keys())
    print(f"Loaded {len(zone_ids)} zones: {zone_ids[0]} → {zone_ids[-1]}")

    # 2. Write 01b_ZoneData.js
    lines = []
    lines.append("// AUTO-GENERATED by scripts/merge_zone_criteria.py — do not edit manually")
    lines.append("// 28 zones × 15 criteria = 420 criteria total")
    lines.append("")
    lines.append("function getDefaultZoneCriteria_() {")
    lines.append("  return {")

    for zid in zone_ids:
        z = merged[zid]
        criteria_map = z["criteria"]  # {"S1": [...], "S2": [...], ...}
        lines.append(f"    {js_str(zid)}: [")
        for pillar in ["S1", "S2", "S3", "S4", "S5"]:
            for c in criteria_map.get(pillar, []):
                en = js_str(c["en"])
                hi = js_str(c["hi"])
                cid = js_str(c["id"])
                lines.append(f"      {{ id: {cid}, pillar: {js_str(pillar)}, labelEn: {en}, labelHi: {hi}, maxScore: 4 }},")
        lines.append("    ],")

    lines.append("  };")
    lines.append("}")
    lines.append("")

    # 3. Also write getDefaultZoneMetadata_() for use in 01_Config.js
    lines.append("")
    lines.append("function getDefaultZoneMetadata_() {")
    lines.append("  return {")

    for zid in zone_ids:
        z = merged[zid]
        leader = z.get("leader", "")
        supervisor = z.get("supervisor", "")
        email = EMAILS.get(leader, leader.lower().replace(" ", ".").replace("mr.", "").replace("mrs.", "").strip() + "@packmasters.in")
        day, daynum = AUDIT_DAYS.get(zid, ("Monday", 1))
        dept = DEPARTMENTS.get(zid, "Production & Ops")
        name = z["name"]
        floor = z.get("floor", "GF")
        # Simple Hindi name: use floor prefix
        name_hi = name  # fallback; can be updated manually
        lines.append(f"    {js_str(zid)}: {{")
        lines.append(f"      id: {js_str(zid)}, name: {js_str(name)}, nameHi: {js_str(name_hi)}, floor: {js_str(floor)},")
        lines.append(f"      leader: {js_str(leader)}, supervisor: {js_str(supervisor)}, email: {js_str(email)},")
        lines.append(f"      auditDay: {js_str(day)}, auditDayNum: {daynum}, department: {js_str(dept)}, driveFolderId: \"\"")
        lines.append("    },")

    lines.append("  };")
    lines.append("}")

    out_path = os.path.join(OUT_DIR, "01b_ZoneData.js")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}")
    print(f"Lines: {len(lines)}")

if __name__ == "__main__":
    main()
